services:
  host1:
    image: alpine
    command: [ sh, -c, "sleep infinity" ]
    networks:
      mynet:
        ipv4_address: 172.28.0.2

  host2:
    image: alpine
    command: [ sh, -c, "sleep infinity" ]
    networks:
      mynet:
        ipv4_address: 172.28.0.3

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
